name: de_walter_app_2
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.0-dev.8
  cached_network_image: ^3.1.0
  jiffy: ^4.1.0
  qr_flutter: ^4.0.0
  uuid: ^3.0.4
  mysql1: ^0.19.2
  qr_code_scanner: ^0.5.2
  dbcrypt: ^2.0.0
  shared_preferences: ^2.0.6
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.8
  intl: ^0.17.0
  flutter_sequence_animation: ^3.0.1





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0




flutter:

  assets:
    - assets/
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf


